---
- hosts: web
  become: yes
  become_user: root
  tasks:
  - name: Install remi repo
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
      state: latest

  - name: Import remi GPG Key
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present

  - name: Install PHP and Httpd
    yum:
      name:
        - httpd
        - php
        - php-cli
        - php-fpm
        - php-mysqlnd
        - php-zip
        - php-devel
        - php-gd
        - php-mcrypt
        - php-mbstring 
        - php-curl
        - php-xml
        - php-pear
        - php-bcmath
        - php-json
      state: latest
      enablerepo: remi-php73

  - name: install nfs-utils
    yum:
      name: nfs-utils
      state: latest

  - name: Started nfs
    service:
      name: nfs-utils
      state: started

  - name: Edit Timezone
    lineinfile:
      path: /etc/php.ini
      regexp: ';date.timezone'
      line: 'date.timezone=Asia/Bangkok'
      backup: yes 

  - name: enableserver create
    template:
      src: 'template/enableserver.conf.j2'
      dest: '/etc/httpd/conf.d/enableserver.conf'

  - name: Create www
    file:
      path: /var/nfs/www
      state: directory
      mode: "0755"

  - name: mount
    command: mount 192.168.100.70:/var/nfs /var/nfs/www

  - name: create web 01 mynet-803.com.conf
    template:
      src: 'template/web-01.mynet-803.com.conf.j2'
      dest: '/etc/httpd/conf.d/web-01.mynet-803.com.conf'
  #  when: ansible_ssh_host == '192.168.100.81'

  - name: create web 01 my-site.com.conf
    template:
      src: 'template/web-01.my-site.com.conf.j2'
      dest: '/etc/httpd/conf.d/web-01.my-site.com.conf'
  #  when: ansible_ssh_host == '192.168.100.81'

  #- name: create web 02 mynet-803.com.conf
   # template:
    #  src: 'template/web-02.mynet-803.com.conf.j2'
     # dest: '/etc/httpd/conf.d/web-02.mynet-803.com.conf'
    #when: ansible_ssh_host == '192.168.100.82'

 # - name: create web 02 my-site.com.conf
  #  template:
   #   src: 'template/web-02.my-site.com.conf.j2'
    #  dest: '/etc/httpd/conf.d/web-02.my-site.com.conf'
    #when: ansible_ssh_host == '192.168.100.82'

  #- name: file web 01 index.php
   # template:
    #  src: 'template/index1.php.j2'
     # dest: '/var/www/mynet-803.com/html/index.php'
   # when: ansible_ssh_host == '192.168.100.81' 
    
  #- name: file web 01 index.php
  #  template:
  #    src: 'template/index2.php.j2'
   #   dest: '/var/www/my-site.com/html/index.php'
    #when: ansible_ssh_host == '192.168.100.81'

 # - name: file web 02 index.php
  #  template:
   #   src: 'template/index3.php.j2'
    #  dest: '/var/www/mynet-803.com/html/index.php'
    #when: ansible_ssh_host == '192.168.100.82' 
    
#  - name: file web 02 index.php
 #   template:
  #    src: 'template/index4.php.j2'
   #   dest: '/var/www/my-site.com/html/index.php'
    #when: ansible_ssh_host == '192.168.100.82'

  - name: Enable httpd
    service:
      name: httpd
      enabled: yes
    
  - name: Start httpd
    service:
      name: httpd
      state: started

  - name: Enable service firewall
    service:
      name: firewalld
      enabled: yes
  
  - name: Start firewall
    service:
      name: firewalld
      state: started

  - name: Open firewall
    firewalld:
      port: '{{ item }}'
      permanent: yes
      state: enabled
    loop:
    - "80/tcp"
    - "443/tcp"
  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted

 